version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: ichbooking_db
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p${DB_PASSWORD} || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    image: 690364538694.dkr.ecr.eu-west-1.amazonaws.com/ichbooking-web:prod
    container_name: ichbooking_web
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${WEB_PORT:-80}:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1:${PORT:-8000}/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s

volumes:
  db_data: