[pytest]
# Позволяет pytest-django автоматически найти Django-проект (ищет manage.py / settings.py)
django_find_project = true

# Добавим src в путь поиска модулей для запусков вне tox
pythonpath = src

# Где лежат тесты (судя по структуре — в src/*/tests)
testpaths =
    src

# Добавим базовые опции тест-рана (можно менять по вкусу)
addopts =
    -ra
    --strict-markers
#    --dotenv=.env
    --disable-warnings

env_files =
    .env

# явно указываем путь к настройкам DJANGO
DJANGO_SETTINGS_MODULE = core.settings