#!/bin/bash
set -e

cat <<EOF > .env
DJANGO_DEBUG=${DJANGO_DEBUG}
DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS}
DJANGO_SECURE_COOKIES=${DJANGO_SECURE_COOKIES}
DOMAIN=${DOMAIN}
WEB_PORT=${WEB_PORT}
DB_ENGINE=${DB_ENGINE}
DB_NAME=${DB_NAME}
DB_TEST_NAME=${DB_TEST_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
JWT_ACCESS_COOKIE_NAME=${JWT_ACCESS_COOKIE_NAME}
JWT_REFRESH_COOKIE_NAME=${JWT_REFRESH_COOKIE_NAME}
JWT_COOKIE_SAMESITE=${JWT_COOKIE_SAMESITE}
JWT_COOKIE_SECURE=${JWT_COOKIE_SECURE}
JWT_ACCESS_LIFETIME_MIN=${JWT_ACCESS_LIFETIME_MIN}
JWT_REFRESH_LIFETIME_DAYS=${JWT_REFRESH_LIFETIME_DAYS}
RUN_MIGRATIONS=${RUN_MIGRATIONS}
RUN_COLLECTSTATIC=${RUN_COLLECTSTATIC}
EOF
