# Generated by Django 5.2.5 on 2025-08-13 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('region', models.CharField(db_index=True, max_length=120)),
                ('country', models.CharField(default='DE', max_length=2)),
                ('price_cents', models.PositiveIntegerField(db_index=True)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('housing_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('room', 'Room'), ('other', 'Other')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accommodations',
                'indexes': [models.Index(fields=['is_active', 'price_cents'], name='accommodati_is_acti_663a07_idx'), models.Index(fields=['city', 'region'], name='accommodati_city_467c71_idx'), models.Index(fields=['created_at'], name='accommodati_created_622039_idx')],
            },
        ),
    ]
