# Generated by Django 5.2.5 on 2025-08-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='impression_count',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
