# Generated by Django 5.2.5 on 2025-08-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_accommodation_impression_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='impression_count',
            new_name='impressions_count',
        ),
    ]
