# Generated by Django 5.2.5 on 2025-08-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_rename_impression_count_accommodation_impressions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='views_count',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
