# Generated by Django 5.2.5 on 2025-08-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0004_accommodation_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Средний рейтинг 1.00..5.00', max_digits=3),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество отзывов по объявлению'),
        ),
    ]
