# Generated by Django 5.2.5 on 2025-08-15 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('region', models.CharField(blank=True, default='', max_length=120)),
                ('price_min', models.FloatField(blank=True, null=True)),
                ('price_max', models.FloatField(blank=True, null=True)),
                ('rooms_min', models.IntegerField(blank=True, null=True)),
                ('rooms_max', models.IntegerField(blank=True, null=True)),
                ('housing_types_csv', models.CharField(blank=True, default='', max_length=255)),
                ('query_signature', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_query_logs',
                'indexes': [models.Index(fields=['query_signature', 'created_at'], name='search_quer_query_s_f7986f_idx')],
            },
        ),
    ]
