# Generated by Django 5.2.5 on 2025-08-16 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0004_accommodation_views_count'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='accommodations.accommodation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listing_view_logs',
                'indexes': [models.Index(fields=['accommodation', 'created_at'], name='listing_vie_accommo_64afc5_idx'), models.Index(fields=['user', 'created_at'], name='listing_vie_user_id_16d420_idx')],
            },
        ),
    ]
